spring:
  application:
    name: blps_1
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2-console
  #    url: jdbc:postgresql://localhost:5432/test
  #    username: postgres
  #    password: changeme
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
springdoc:
  swagger-ui:
    operations-sorter: method
    defaultModelsExpandDepth: -1
    tags-sorter: alpha
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
