package com.mascix.mysqlsession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private UserRepository userRepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewUser (@RequestParam String name
      , @RequestParam String email) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    User n = new User();
    n.setName(name);
    n.setEmail(email);
    userRepository.save(n);
    return "Saved";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<User> getAllUsers() {
    // This returns a JSON or XML with the users
    return userRepository.findAll();
  }

  @GetMapping(path="/user/{name}")
  public @ResponseBody User getUserByName(@PathVariable String name) {
    return userRepository.findByName(name);
  }
  @GetMapping(path="/user/native/{name}")
  public @ResponseBody User getUserByNameWithNative(@PathVariable String name) {
    return userRepository.native1(name);
  }

  @GetMapping(path="/user/native/setsession/{name}")
  public @ResponseBody Boolean setSession(@PathVariable String name) {
    userRepository.nativeSessionSet(name);
    return true;
  }

  @GetMapping(path="/user/native/getsession")
  public @ResponseBody Object getSession() {
    return userRepository.nativeSessionGet();
  }


}